# Generated by Django 3.1.1 on 2020-09-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200905_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('grouptype', models.PositiveSmallIntegerField(choices=[(1, '结对作业的组'), (2, '团队项目的组')], default=1, verbose_name='组队类型')),
                ('members', models.TextField(blank=True, verbose_name='组员列表')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader_user', to=settings.AUTH_USER_MODEL, verbose_name='队长')),
            ],
            options={
                'verbose_name': '组队',
                'verbose_name_plural': '组队',
                'ordering': ['-createat'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveSmallIntegerField(null=True, verbose_name='评分')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_group', to='backend.group', verbose_name='对应组')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='对应学生')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater_user', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
            options={
                'verbose_name': '组内评分',
                'verbose_name_plural': '组内评分',
                'ordering': ['-createat'],
            },
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_group', to='backend.group', verbose_name='对应组')),
                ('judger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judger_user', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_user', to=settings.AUTH_USER_MODEL, verbose_name='对应学生')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'ordering': ['-createat'],
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('scorerules', models.TextField(blank=True, verbose_name='得分规则')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('homeworktype', models.PositiveSmallIntegerField(choices=[(0, '单人作业'), (1, '结对作业'), (2, '组队作业')], default=0, verbose_name='作业类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_author_user', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-createat'],
            },
        ),
    ]
