# Generated by Django 3.1.1 on 2020-09-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200906_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='标题'),
        ),
    ]
