# Generated by Django 3.1.1 on 2020-09-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_homework_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_homework', to='backend.homework', verbose_name='对应作业'),
        ),
    ]
