# Generated by Django 3.1.1 on 2020-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_judgement_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupname',
            field=models.CharField(blank=True, max_length=255, verbose_name='队伍名'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='scoredatail',
            field=models.TextField(blank=True, verbose_name='评分详情'),
        ),
    ]
