# Generated by Django 3.1.1 on 2020-09-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200908_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_group', to='backend.group', verbose_name='对应组'),
        ),
    ]
