# Generated by Django 3.1.1 on 2020-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200910_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='createat',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='createat',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
