# Generated by Django 3.1.1 on 2020-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200921_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Token'),
        ),
    ]
