# Generated by Django 3.1.1 on 2020-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_group_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='blogurl',
            field=models.URLField(blank=True, default='#', verbose_name='博客园链接'),
        ),
    ]
