# Generated by Django 3.1.1 on 2020-09-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_homework_blogurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='scoredatail',
            new_name='scoredetail',
        ),
    ]
