# Generated by Django 3.1.1 on 2020-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200930_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='totalscore',
            field=models.FloatField(default=0, verbose_name='总分'),
        ),
    ]
